
version: '3'

services:
  processor:
    build: processor
    links:
      - zookeeper:zk
      - elasticsearch:es
    depends_on:
      - kafka
      - elasticsearch
    command: bash -c "/code/wait.sh && python3 -m processor.service"
    ports:
      - "8443"
    volumes:
      - ./processor:/code

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    depends_on:
      - zookeeper
    environment:
      # Need to specify more partitions than number of workers to actually have parallelism
      # But since there is only one broker here (see discussion in readme) we still only
      # have a replication factor of 1
      KAFKA_CREATE_TOPICS: "places:16:1"
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST}
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
      - ./etc/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

